function(cartosentry_enable_sanitizers target)
  if(NOT CARTOSENTRY_ENABLE_SANITIZERS AND NOT CARTOSENTRY_ENABLE_THREAD_SANITIZER)
    return()
  endif()
  if(CARTOSENTRY_ENABLE_SANITIZERS AND CARTOSENTRY_ENABLE_THREAD_SANITIZER)
    message(FATAL_ERROR "AddressSanitizer and ThreadSanitizer require separate processes")
  endif()
  if(MSVC)
    message(FATAL_ERROR "Sanitizers are currently supported only by Clang and GCC")
  endif()
  if(CARTOSENTRY_ENABLE_THREAD_SANITIZER)
    target_compile_options("${target}" PRIVATE -fsanitize=thread -fno-omit-frame-pointer)
    target_link_options("${target}" PRIVATE -fsanitize=thread)
    return()
  endif()
  target_compile_options("${target}" PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
  target_link_options("${target}" PRIVATE -fsanitize=address,undefined)
endfunction()

function(cartosentry_enable_coverage target)
  if(NOT CARTOSENTRY_ENABLE_COVERAGE)
    return()
  endif()
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    message(FATAL_ERROR "Coverage requires Clang or GCC")
  endif()
  target_compile_options("${target}" PRIVATE --coverage -O0 -g)
  target_link_options("${target}" PRIVATE --coverage)
endfunction()
