function(cartosentry_enable_sanitizers target)
  if(NOT CARTOSENTRY_ENABLE_SANITIZERS)
    return()
  endif()
  if(MSVC)
    message(FATAL_ERROR "The sanitizer preset is currently supported only by Clang and GCC")
  endif()
  target_compile_options("${target}" PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
  target_link_options("${target}" PRIVATE -fsanitize=address,undefined)
endfunction()

function(cartosentry_enable_coverage target)
  if(NOT CARTOSENTRY_ENABLE_COVERAGE)
    return()
  endif()
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    message(FATAL_ERROR "Coverage requires Clang or GCC")
  endif()
  target_compile_options("${target}" PRIVATE --coverage -O0 -g)
  target_link_options("${target}" PRIVATE --coverage)
endfunction()
